// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5-hrpcoU47Zr6GE-JhLXStmSuBIsMRws',
    appId: '1:631990539487:web:af487b4247b3a91d13c56a',
    messagingSenderId: '631990539487',
    projectId: 'videonest-40042',
    authDomain: 'videonest-40042.firebaseapp.com',
    storageBucket: 'videonest-40042.firebasestorage.app',
    measurementId: 'G-F56TGBWJJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkQkJ4QyYs2DSSlyzvp9lWMpdzZK9UpwM',
    appId: '1:631990539487:android:fdc1d207b5642f5413c56a',
    messagingSenderId: '631990539487',
    projectId: 'videonest-40042',
    storageBucket: 'videonest-40042.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPYI1WhK4iV0-jG4bFJI8qXaqmY8vli18',
    appId: '1:631990539487:ios:ed570f70e8297a8613c56a',
    messagingSenderId: '631990539487',
    projectId: 'videonest-40042',
    storageBucket: 'videonest-40042.firebasestorage.app',
    iosBundleId: 'com.example.videonest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPYI1WhK4iV0-jG4bFJI8qXaqmY8vli18',
    appId: '1:631990539487:ios:ed570f70e8297a8613c56a',
    messagingSenderId: '631990539487',
    projectId: 'videonest-40042',
    storageBucket: 'videonest-40042.firebasestorage.app',
    iosBundleId: 'com.example.videonest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5-hrpcoU47Zr6GE-JhLXStmSuBIsMRws',
    appId: '1:631990539487:web:fd1adb2fa8e6058f13c56a',
    messagingSenderId: '631990539487',
    projectId: 'videonest-40042',
    authDomain: 'videonest-40042.firebaseapp.com',
    storageBucket: 'videonest-40042.firebasestorage.app',
    measurementId: 'G-QX8ESK9X0L',
  );
}
